version: '3.4'

services:
  lagroce:
    image: lagroce
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3004:3004
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
